// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using solardash.Server.Data;

#nullable disable

namespace solardash.Server.Migrations
{
    [DbContext(typeof(SolarDbContext))]
    [Migration("20250505084402_TimescaleSetup")]
    partial class TimescaleSetup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("solardash.Server.Models.HourlyStats", b =>
                {
                    b.Property<double?>("AvgExpectedPower")
                        .HasColumnType("double precision")
                        .HasColumnName("avg_expected_power");

                    b.Property<double?>("AvgPower")
                        .HasColumnType("double precision")
                        .HasColumnName("avg_power");

                    b.Property<double?>("AvgPowerLoss")
                        .HasColumnType("double precision")
                        .HasColumnName("avg_power_loss");

                    b.Property<DateTime>("Hour")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hour");

                    b.Property<double?>("MaxIrradiance")
                        .HasColumnType("double precision")
                        .HasColumnName("max_irradiance");

                    b.ToTable("hourly_stats", t =>
                        {
                            t.ExcludeFromMigrations();
                        });

                    b.ToView("hourly_stats", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
